-- MySQL Script generated by MySQL Workbench
-- Tue Feb  2 00:47:05 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IntroNet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IntroNet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IntroNet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IntroNet` ;

-- -----------------------------------------------------
-- Table `IntroNet`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Event` (
  `Event_id` INT UNSIGNED NULL AUTO_INCREMENT,
  `Event_name` VARCHAR(45) NOT NULL,
  `Time` TIME NOT NULL,
  `Date` DATE NOT NULL,
  `meeting_rounds` INT UNSIGNED NULL,
  `poster_rounds` INT UNSIGNED NULL,
  PRIMARY KEY (`Event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Organisation` (
  `organisation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `event` INT UNSIGNED NULL,
  PRIMARY KEY (`organisation_id`),
  INDEX `fk_event_idx` (`event` ASC),
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event`)
    REFERENCES `IntroNet`.`Event` (`Event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Participant` (
  `participant_id` INT UNSIGNED NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `organisation` INT UNSIGNED NOT NULL,
  `biography` LONGTEXT NULL,
  `icebreaker_question` VARCHAR(45) NULL,
  PRIMARY KEY (`participant_id`),
  INDEX `fk_org_idx` (`organisation` ASC),
  CONSTRAINT `fk_org`
    FOREIGN KEY (`organisation`)
    REFERENCES `IntroNet`.`Organisation` (`organisation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Poster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Poster` (
  `Poster_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `presented_by` INT NOT NULL,
  `event` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Poster_id`),
  INDEX `fk_Poster_Participant1_idx` (`presented_by` ASC),
  INDEX `event_idx` (`event` ASC),
  CONSTRAINT `event`
    FOREIGN KEY (`event`)
    REFERENCES `IntroNet`.`Event` (`Event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poster_Participant1`
    FOREIGN KEY (`presented_by`)
    REFERENCES `IntroNet`.`Participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Table` (
  `number` INT NOT NULL,
  `event` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`number`, `event`),
  INDEX `fk_event_idx` (`event` ASC),
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event`)
    REFERENCES `IntroNet`.`Event` (`Event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Meeting_round`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Meeting_round` (
  `round` INT UNSIGNED NOT NULL,
  `table` INT NOT NULL,
  `first_person` INT UNSIGNED NOT NULL,
  `second_person` INT UNSIGNED NULL,
  PRIMARY KEY (`round`, `table`),
  INDEX `fk_table_idx` (`table` ASC),
  INDEX `fk_fperson_idx` (`first_person` ASC),
  INDEX `fk_sperson_idx` (`second_person` ASC),
  CONSTRAINT `fk_table`
    FOREIGN KEY (`table`)
    REFERENCES `IntroNet`.`Table` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fperson`
    FOREIGN KEY (`first_person`)
    REFERENCES `IntroNet`.`Participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sperson`
    FOREIGN KEY (`second_person`)
    REFERENCES `IntroNet`.`Participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Registration` (
  `participant` INT UNSIGNED NOT NULL,
  `event` INT UNSIGNED NOT NULL,
  `weight` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`participant`, `event`),
  INDEX `fk_event_idx` (`event` ASC),
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event`)
    REFERENCES `IntroNet`.`Event` (`Event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant`
    FOREIGN KEY (`participant`)
    REFERENCES `IntroNet`.`Participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Attending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Attending` (
  `event` INT UNSIGNED NOT NULL,
  `participant` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`event`, `participant`),
  INDEX `fk_participant_idx` (`participant` ASC),
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event`)
    REFERENCES `IntroNet`.`Event` (`Event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant`
    FOREIGN KEY (`participant`)
    REFERENCES `IntroNet`.`Participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntroNet`.`Poster_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntroNet`.`Poster_visit` (
  `round` INT UNSIGNED NOT NULL,
  `poster` INT UNSIGNED NOT NULL,
  `participant` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`round`, `poster`, `participant`),
  INDEX `fk_poster_idx` (`poster` ASC),
  INDEX `fk_participant_idx` (`participant` ASC),
  CONSTRAINT `fk_poster`
    FOREIGN KEY (`poster`)
    REFERENCES `IntroNet`.`Poster` (`event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant`
    FOREIGN KEY (`participant`)
    REFERENCES `IntroNet`.`Participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
